#Prod Ortamı Konfigürasyonu
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: countries-be
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #format_sql: true
      #dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        jdbc.batch_size: 20
        cache.use_query_cache: false
        cache.use_second_level_cache: false
        cache.use_structured_entries: false
        cache.use_minimal_puts: false
    show-sql: true
    open-in-view: false